### ISSUE TITLE
Remove empty statements in Lua 5.1

### ISSUE THREAD

**Issue by hydroper** [oxyc/luaparse#42]
In Lua 5.1 empty statements can only appear at the end of a statement.
Check this: https://www.lua.org/manual/5.1/manual.html#2.4.1

I made two pull requests, but both got closed. You guys are bad.

**Comment by hydroper** [comment]
@fstirlitz Stop being ignorant, you look a super kid!!! I didn't change the name of the repeatStatement, it was my editor's ReplaceAll tool.

**Comment by hydroper** [comment]
You're stupid enough.

**Comment by hydroper** [comment]
I adviced you, but continue ignoring my advices.

**Comment by hydroper** [comment]
I know how to use GitHub better than you. AND again, the make test blah command ISN'T VALID in my command prompt. I ran `npm install` , in luaparse's root, but NOTHING.

**Comment by hydroper** [comment]
I adviced you this many times, but continue with this such stupid and demonic ignorance.

**Comment by hydroper** [comment]
There's no reason to continue fixing bugs in this shit of luaparse.

**Comment by oxyc** [comment]
[`make`](https://www.gnu.org/software/make/manual/make.html) is a *nix build tool that the project uses. It's unrelated to node, but definitely worth learning as it's widely used.

Sorry you feel that way. I do agree with @fstirlitz, and the PR was not mergeable as it was. Thanks for your work though, and we might pick it up if we have the time later on.

**Comment by fstirlitz** [comment]
Fixed in 1a144cea96fce1c658eebe24dad9fb44b9de851c. Go see how your commit should have looked like.

> You're stupid enough.

> I adviced you this many times, but continue with this such stupid and demonic ignorance.

> There's no reason to continue fixing bugs in this shit of luaparse.

I likewise hope you also have a lovely day!!!!!!!1111💖💖💖💖💖💖💖😻😻😻
