### ISSUE TITLE
PrefixExpression off-by-one in the range of IndexExpressions

### ISSUE THREAD

**Issue by trixnz** [oxyc/luaparse#48]
`parsePrefixExpression` is returning `IndexExpression`s with a range ending one character before the actual end of the expression. I suspect this is because the node [is finished](https://github.com/oxyc/luaparse/blob/bf23bdf8a5b3963ba403e0600c7a24be9b01e803/luaparse.js#L2086) before consuming the closing `]`.

**Comment by fstirlitz** [comment]
Fixed by a1114d312d09df280bc43b50a254679ca64e22a5, thank you.
