### ISSUE TITLE
404 : https://github.com/hydroper/luaparse-ts

### ISSUE THREAD

**Issue by zaoqi** [oxyc/luaparse#59]

**Comment by fstirlitz** [comment]
Huh, apparently the project is deleted. I'll remove the link.

**Comment by Teoxoy** [comment]
TS definitions are at [`@types/luaparse`](https://www.npmjs.com/package/@types/luaparse) 

I don't think it's necessary to mention it in the readme - most typescript users check for types on https://microsoft.github.io/TypeSearch/ anyway.
