### ISSUE TITLE
Incorrect uses of goto are not detected

### ISSUE THREAD

**Issue by Teoxoy** [oxyc/luaparse#71]
I think it makes sense for luaparse to throw these errors. Lua throws them at compile time too.

#### Examples with respective errors
_tests from [goto test file in lua repo](https://github.com/lua/lua/blob/89aee84cbc9224f638f3b7951b306d2ee8ecb71e/testes/goto.lua#L6-L40)_

```lua
goto l1; do ::l1:: end
```

```lua
do ::l1:: end goto l1;
```

Error: `no visible label 'l1' for <goto>`

---

```lua
::l1:: ::l1::
```

Error: `label 'l1' already defined`

---

```lua
goto l1; local aa ::l1:: ::l2:: print(3)
```

```lua
do local bb, cc; goto l1; end; local aa; ::l1:: print(3)
```

Error: `<goto l1> at line 1 jumps into the scope of local 'aa'`

---

```lua
repeat
    if x then goto cont end
    local xuxu = 10
    ::cont::
  until xuxu < x
```

Error: `<goto cont> at line 2 jumps into the scope of local 'xuxu'`

---

#### Quote from [lua manual](https://www.lua.org/manual/5.3/manual.html#3.3.4) regarding this

> A label is visible in the entire block where it is defined, except inside nested blocks where a label with the same name is defined and inside nested functions. A goto may jump to any visible label as long as it does not enter into the scope of a local variable.

---

I am currently looking into implementing this in my own project based on the AST generated by luaparse. I can start a PR for it here as soon as I have something working.

**Comment by fstirlitz** [comment]
Fixed in 680238cac4b4bb0648413d069450fe73f45118a9.
